### ISSUE TITLE
The binary doesn't work on alpine

### ISSUE THREAD

**Issue by dividedmind** [conjurinc/summon-s3#1]
The binary does not work on alpine linux:

``` sh-session
# ./summon-s3
sh: ./summon-s3: not found
```

It seems it's because of glibc dependency. To fix it, the binary should either be statically compiled, or a separate binary for musl should be provided.

(Originally reported by @chrisdostert as https://github.com/conjurinc/summon/issues/20)

**Comment by dustinmm80** [comment]
This is resolved with [v0.2.0](https://github.com/conjurinc/summon-s3/releases/tag/v0.2.0). We now build an alpine binary with the `golang:1.9-alpine` Docker image.
