### ISSUE TITLE
ECS task roles error

### ISSUE THREAD

**Issue by slimm609** [conjurinc/summon-s3#2]
summon s3 won't pull from a container with ECS roles because the version of aws-sdk-go is to old to support it.       A rebuild with updated deps should resolve the issue.  

I tried to update all the deps but I am getting these errors below while building.   I don't know go well enough to resolve this issue. 

```-->    darwin/amd64: github.com/conjurinc/summon-s3
-->     linux/amd64: github.com/conjurinc/summon-s3
-->   windows/amd64: github.com/conjurinc/summon-s3

3 errors occurred:
--> darwin/amd64 error: exit status 2
Stderr: # github.com/aws/aws-sdk-go/aws/request
Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/request/request_context_1_6.go:13: r.HTTPRequest.Cancel undefined (type *http.Request has no field or method Cancel)

--> linux/amd64 error: exit status 2
Stderr: # github.com/aws/aws-sdk-go/aws/request
Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/request/request_context_1_6.go:13: r.HTTPRequest.Cancel undefined (type *http.Request has no field or method Cancel)

--> windows/amd64 error: exit status 2
Stderr: # github.com/aws/aws-sdk-go/aws/request
Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/request/request_context_1_6.go:13: r.HTTPRequest.Cancel undefined (type *http.Request has no field or method Cancel)
```

**Comment by slimm609** [comment]
I thought I had it solved but even updating to go1.7, it is still throwing the error.

**Comment by slimm609** [comment]
I was able to get it to compile with 1.7 but it throws this error now 

error fetching variable AWS: exit status 2: panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x46e4da]

goroutine 1 [running]:
panic(0x6b3b20, 0xc420012080)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
github.com/aws/aws-sdk-go/service/s3.New(0x0, 0x0, 0x0, 0x0, 0x0, 0xc4200cf460)
	/go/src/github.com/conjurinc/summon-aws/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/s3/service.go:47 +0x3a
main.main()
	/go/src/github.com/conjurinc/summon-aws/main.go:38 +0x189

**Comment by dustinmm80** [comment]
Thanks for bringing this up! Will get a new build out later today.

**Comment by slimm609** [comment]
i doubt this is correct but   I added this 
```"github.com/aws/aws-sdk-go/aws/session"```
and
```sess := session.Must(session.NewSession())
	// Create S3 service client
	svc := s3.New(sess)
```
and it makes it work with ECS task roles but it no longer works with the ~/.aws/credentials files 

so I sure there is more to be changed to work with both.    

I can test both use cases easily if needed.   

Thanks!

**Comment by slimm609** [comment]
I also had to build it with the golang docker image because the gox image was giving problems.   (used the image that summon is using)

**Comment by dustinmm80** [comment]
This commit should fix the build errors: https://github.com/conjurinc/summon-s3/commit/109346ec378a9808973ac46988364b0b37780b25.

Can you try latest master and let us know if you're still seeing issues?

**Comment by slimm609** [comment]
will do

**Comment by slimm609** [comment]
this is the error that I am getting

```
Error fetching variable VAR: exit status 2: panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6a776a]

    goroutine 1 [running]:
 summon-s3/vendor/github.com/aws/aws-sdk-go/service/s3.New(0x0, 0x0, 0x0, 0x0, 0x0, 0xc420016240)
 	/go/src/summon-s3/vendor/github.com/aws/aws-sdk-go/service/s3/service.go:47 +0x3a
 main.main()
 	/go/src/summon-s3/main.go:38 +0x181
```

**Comment by slimm609** [comment]
I'm not sure how to do it in go but something similar to this is what i was thinking

```
       // if config file exists
	sess := session.Must(session.NewSessionWithOptions(session.Options{
		SharedConfigState: session.SharedConfigEnable,
	}))
      
	if sess == nil {
                // if session token exists
		sess := session.Must(session.NewSession())
	}
       
        svc := s3.New(sess)
```

**Comment by slimm609** [comment]
I just put up an MR that resolves it

**Comment by dustinmm80** [comment]
PR #3 has been merged to address this. v0.2.0 should work fine with ECS tasks. Please reopen if this is not the case. Thanks for your contribution @slimm609!
