### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by eucj** [conjurinc/summon-s3#5]
It'd be great if installation instructions could be added/linked to in README.

**Comment by slimm609** [comment]
the link on the readme tells you how to install it.   

[Set summon-s3 as your Summon provider.](https://github.com/cyberark/summon#flags)

**Comment by sgnn7** [comment]
@eucj Thanks for your report!

Sadly, I agree with @slimm609 here that the instructions are decently well documented in the README so I'll close this issue as a won't-fix. If you find yourself needing specific type of installation instructions that are missing, feel free to open new issues for those!
